[build]
builder = "nixpacks"
buildCommand = "echo 'Building from railway.toml' && npm run build"

[deploy]
startCommand = "echo 'Starting from railway.toml' && npm run start:cron"
healthcheckPath = "/"
healthcheckTimeout = 100

[[cron]]
schedule = "* * * * *"
command = "echo 'Running cron job from railway.toml' && curl -X GET -H 'Authorization: Bearer $CRON_SECRET_KEY' $RAILWAY_PUBLIC_DOMAIN/api/cron/update-prices"
